/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Plugin {
  title?: string;
  name?: string;
  type?: string;
  topic?: unknown[];
  description?: string;
  query?: {
    definition?: string;
    template?: string;
    ignoreCache?: boolean;
    [k: string]: unknown;
  };
  render?: {
    cache?: {
      ttl?: number;
      [k: string]: unknown;
    };
    src?: string;
    [k: string]: unknown;
  };
  author?: string[];
  shared?: boolean;
}
