name: Create Plugin PR

on:
  workflow_dispatch:
    inputs:
      plugin:
        description: 'Plugin name'
        required: true
        type: string
      sql:
        description: 'SQL string'
        required: true
        type: string
      js:
        description: 'js code'
        required: true
        type: string
      option:
        description: 'echart option'
        required: true
        type: string

jobs:
  create-plugin-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'czhen-bot/hackathon2022-ossinsight-marketplace'
          ref: 'main'
          token: ${{ secrets.CZHEN_BOT_GH_TOKEN }}
          path: 'bot_repo'
      - name: create a new branch and commit
        run: |
          cd bot_repo
          git config user.name github-actions
          git config user.email github-actions@github.com

          git checkout -b ${{ inputs.plugin }}

          sudo mkdir -p plugins/${{ inputs.plugin }}
          echo ${{ inputs.sql }} > plugins/${{ inputs.plugin }}/query.sql
          echo ${{ inputs.js }} > plugins/${{ inputs.plugin }}/index.js
          echo ${{ inputs.option }} > plugins/${{ inputs.plugin }}/option.js

          git add plugins/${{ inputs.plugin }}
          git commit -m "add plugin ${{ inputs.plugin }}"
          git push -u origin ${{ inputs.plugin }}

      - name: create pr
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.CZHEN_BOT_GH_TOKEN }}" \                                                
          https://api.github.com/repos/shczhen/hackathon2022-ossinsight-marketplace/pulls \
          -d '{"title":"[plugin] ${{ inputs.plugin }}","body":"Please pull these awesome changes in!","head":"czhen-bot:hackathon2022-ossinsight-marketplace:${{ inputs.plugin }}","base":"main"}'
